### ISSUE TITLE
Error: Cannot find module './fs'

### ISSUE THREAD

**Issue by meabed** [runk/node-maxmind#174]
Latest version 3.0.1 has an issue in here
```
const fs_1 = __importDefault(require("./fs"));
```

**Comment by lozadavictor** [comment]
i'm having the same problem ! 

```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module './fs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/lonlatsql/node_modules/maxmind/lib/index.js:7:30)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**Comment by AuspeXeu** [comment]
Same problem. Library not usable as of now.

**Comment by runk** [comment]
Damn. Let me look into it. Do you use vanilla js or babel/tsc etc?

**Comment by donovanh** [comment]
Seeing the error here on a new Svelte project, vanilla JS

**Comment by runk** [comment]
v3.0.2 is there, should be resolved
