### ISSUE TITLE
LRU.evict error

### ISSUE THREAD

**Issue by coderslagoon** [runk/node-maxmind#180]
3.0.3, `get("194.95.119.9")`, using database:

61030828 May  6 09:32 GeoLite2-City.mmdb

retrieved from https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
(SHA: 17b408d9132881aedd85db744fa8b18ed8b226af)

The following error occurs:

```
    TypeError: Cannot set property 'prev' of null

      at LRU.evict (node_modules/tiny-lru/lib/tiny-lru.js:68:20)
      at LRU.set (node_modules/tiny-lru/lib/tiny-lru.js:125:11)
      at Decoder.decodeFast (node_modules/maxmind/src/decoder.ts:93:16)
      at Decoder.decode (node_modules/maxmind/src/decoder.ts:67:26)
      at Decoder.decodeMap (node_modules/maxmind/src/decoder.ts:274:18)
      at Decoder.decodeByType (node_modules/maxmind/src/decoder.ts:113:21)
      at Decoder.decode (node_modules/maxmind/src/decoder.ts:83:17)
      at Decoder.decodeFast (node_modules/maxmind/src/decoder.ts:92:25)
      at Decoder.decode (node_modules/maxmind/src/decoder.ts:67:26)
      at Decoder.decodeMap (node_modules/maxmind/src/decoder.ts:276:18)
```

**Comment by runk** [comment]
I'll look into it.

**Comment by coderslagoon** [comment]
Looks like it has to do with the test case setting `options.cache.max=1`. Picking a more reasonable(?) size like 1000 seems to work.
