### ISSUE TITLE
Resolving for invalid ip (random string) throws an error

### ISSUE THREAD

**Issue by marinbek** [runk/node-maxmind#22]
Trying to resolve some random string like `bla` throws following error:

For e.g. `location.getLocation('bla');` it throws:

```
 [RangeError: Trying to access beyond buffer length] (in geo_maxmind.js:33)
Call Stack:
    at exports.GeoSolver.noode.Class.extend.solve (/home/ubuntu/fetch/src/utils/geo_maxmind.js:33:20)
    at Object.<anonymous> (/home/ubuntu/fetch/src/fetch.js:27:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

**Comment by runk** [comment]
https://github.com/runk/node-maxmind/pull/32
