### ISSUE TITLE
Library throws when doing lookups again paid Maxmind databases

### ISSUE THREAD

**Issue by rixth** [runk/node-maxmind#46]
The exact error is "Error: Unknown type undefined at offset 142683025". The offset changes depending on which IP I am trying to geolocate.

I am pulling the database like so:

```
curl "https://download.maxmind.com/app/geoip_download?edition_id=GeoIP2-City&suffix=tar.gz&license_key=$MAXMIND_KEY" > GeoIP-City.mmdb.gz
# Ensure GeoIP-City.mmdb.gz's md5 matches what is provided
cat GeoIP-city.mmdb.gz | gunzip > GeoIP-city.mmdb
```

```
const maxmind = require('maxmind');
const cityIpLookup = maxmind.open('path/to/GeoIP-city.mmdb');

Reader {
  cache:
   LRUCache {
     max: 50000,
     maxAge: 3600000
   },
  db: <Buffer 47 65 6f 49 50 32 2d 43 69 74 79 5f 32 30 31 36 30 38 31 36 2f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... >,
  metadata:
   Metadata {
     binaryFormatMajorVersion: 2,
     binaryFormatMinorVersion: 0,
     buildEpoch: 2016-08-15T13:59:24.000Z,
     databaseType: 'GeoIP2-City',
     languages: [ 'de', 'en', 'es', 'fr', 'ja', 'pt-BR', 'ru', 'zh-CN' ],
     description: { en: 'GeoIP2 City database' },
     ipVersion: 6,
     nodeCount: 11815856,
     recordSize: 28,
     nodeByteSize: 7,
     searchTreeSize: 82710992,
     treeDepth: 128 },
  decoder:
   Decoder {
     db: <Buffer 47 65 6f 49 50 32 2d 43 69 74 79 5f 32 30 31 36 30 38 31 36 2f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... >,
     baseOffset: 82711008 },
  readNodeLeft: [Function],
  readNodeRight: [Function] }

> cityIpLookup.get('172.58.73.96')

Error: Unknown type undefined at offset 142683025
    at Decoder.decodeByType (/Users/trix/workspace/cpf/app/node_modules/maxmind/lib/decoder.js:105:9)
    at Decoder.decode (/Users/trix/workspace/cpf/app/node_modules/maxmind/lib/decoder.js:62:15)
    at Reader.resolveDataPointer (/Users/trix/workspace/cpf/app/node_modules/maxmind/lib/reader.js:160:29)
    at Reader.get (/Users/trix/workspace/cpf/app/node_modules/maxmind/lib/reader.js:52:25)
    at repl:1:6
    at sigintHandlersWrap (vm.js:32:31)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInContext (vm.js:31:12)
    at REPLServer.defaultEval (repl.js:308:29)
    at bound (domain.js:280:14)
```

**Comment by rixth** [comment]
Through a little console.log debugging, when I run `db.get('172.58.73.96')` `Reader.decode` is called with `offset` equal to `142683025`.

The `type` is set to `extended`, the `if type == extended` branch runs `tmp = this.db[offset] + 7` which ends up as a `NaN`. This is not a valid index of the `types` array, hence `undefined`.

**Comment by runk** [comment]
Can you please confirm that mmdb file isn't broken and md5 signature matches?

**Comment by runk** [comment]
.. or that comment means that you actually confirmed it?

```
# Ensure GeoIP-City.mmdb.gz's md5 matches what is provided
```

Is it possible you can share the mmdb file somehow?

**Comment by rixth** [comment]
Yeah, the md5 of the `tar.gz` matches Maxmind's md5. When I open the `mmdb` in a hex viewer, it doesn't look obviously corrupted ![](http://i.trix.io/qamq621n.png)

Drop me an email (thomas@trix.io) or DM (@rx) and I can share the file with you.

**Comment by runk** [comment]
It looks legit in hex editor - exactly how search tree should look like.

I've been doing debugging and decided to try the official library and compare results. Even official python lib http://geoip2.readthedocs.io/ doesn't work with your database:

```python
import geoip2.database
reader = geoip2.database.Reader('GeoIp-City.mmdb')
response = reader.city('172.58.73.96')
```

output:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    response = reader.city('172.58.73.96')
  File "/Library/Python/2.7/site-packages/geoip2/database.py", line 110, in city
    return self._model_for(geoip2.models.City, 'City', ip_address)
  File "/Library/Python/2.7/site-packages/geoip2/database.py", line 180, in _model_for
    record = self._get(types, ip_address)
  File "/Library/Python/2.7/site-packages/geoip2/database.py", line 173, in _get
    record = self._db_reader.get(ip_address)
  File "/Library/Python/2.7/site-packages/maxminddb/reader.py", line 106, in get
    return self._resolve_data_pointer(pointer) if pointer else None
  File "/Library/Python/2.7/site-packages/maxminddb/reader.py", line 175, in _resolve_data_pointer
    "The MaxMind DB file's search tree is corrupt")
maxminddb.errors.InvalidDatabaseError: The MaxMind DB file's search tree is corrupt
```

**Comment by runk** [comment]
Can you get the fresh db and try it out?

**Comment by rixth** [comment]
Weird -- the md5 matched, though! I tried two different dates of the db, both gave the same error (but different offsets).

**Comment by runk** [comment]
What confuses me is same behavior with official libraries..

**Comment by rixth** [comment]
Figured it out. The `.mmdb.gz`file is a tarball with a directory and files inside. `gunzip` was creating a tarball, not the db itself. If you then pipe it to `tar -xvf` you get the directory structure, and a workable database.

```❯❯❯ cat GeoIP-City.mmdb.gz | gunzip | tar -xvf -
x GeoIP2-City_20160823/
x GeoIP2-City_20160823/GeoIP2-City.mmdb
x GeoIP2-City_20160823/COPYRIGHT.txt
x GeoIP2-City_20160823/LICENSE.txt```

Closing! Thanks for your help, @runk.
