### ISSUE TITLE
Error: Maxmind v2 module has changed API.

### ISSUE THREAD

**Issue by aphorise** [runk/node-maxmind#565]
I have `GeoLite2-City.mmdb` & others and am trying the example as per the [README.md](https://github.com/runk/node-maxmind#javascript) - however it keeps resulting in:

```bash
node test.js 8.8.8.8
  # ../node-test/node_modules/maxmind-4.3.6/lib/index.js:66
  #     throw new Error(utils_1.default.legacyErrorMessage);
  #     ^
  # 
  # Error: Maxmind v2 module has changed API.
  # Upgrade instructions can be found here: https://github.com/runk/node-maxmind/wiki/Migration-guide
  # If you want to use legacy libary then explicitly install maxmind@1
  #     at Object.openSync (../node-test/node_modules/maxmind-4.3.6/lib/index.js:66:11)
  #     at Object.<anonymous> (../node-test/vipi.js:38:6)
  #     at Module._compile (node:internal/modules/cjs/loader:1105:14)
  #     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
  #     at Module.load (node:internal/modules/cjs/loader:981:32)
  #     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  #     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
  #     at node:internal/main/run_main_module:17:4
```

My source is as follows:
```javascript
# // using: 4.3.6
mMAX = require("maxmind");
mMAX.open('./test_dbs/GeoLite2-City.mmdb').then((lookup2) => {
	console.log(lookup2.get('66.6.44.4'));
	console.log(lookup2.getWithPrefixLength('66.6.44.4'));
  });

// also tried - same thing:
mMAX.openSync('./test_dbs/GeoLite2-City.mmdb').then((lookup2) => {
```

What am I doing wrong or missing?

**Comment by aphorise** [comment]
Nevermind this was an issue with me.
