### ISSUE TITLE
Loading an invalid mmdb file causes an unhandled exception

### ISSUE THREAD

**Issue by RavivIsraeli** [runk/node-maxmind#70]
uncaughtException:  Error: Unknown type undefined at offset 1
    at Decoder.decodeByType (/build/node_modules/maxmind/lib/decoder.js:105:9)
    at Decoder.decode (/build/node_modules/maxmind/lib/decoder.js:62:15)
    at new Metadata (/build/node_modules/maxmind/lib/metadata.js:15:26)
    at Reader.load (/build/node_modules/maxmind/lib/reader.js:27:19)
    at new Reader (/build/node_modules/maxmind/lib/reader.js:21:8)
    at /build/node_modules/maxmind/index.js:22:18
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3) 

The code in the reader should catch this and eventually call the callback for the "open" command with the error instead of throwing an unhandled exception

**Comment by antishov** [comment]
Can you attach example of invalid database?

**Comment by RavivIsraeli** [comment]
An empty file for example... If i try to load an empty file it shouldn't throw an unhandled exception and crash the entire process. 
It should simply return an error.

**Comment by antishov** [comment]
PR #71

**Comment by runk** [comment]
Fixed in #76
