### ISSUE TITLE
 Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by pranshu1992** [runk/node-maxmind#73]
/Users/prkumar/Projects/pre-pin-backend/db/maxmind.js:5
  var city = cityLookup.get('66.6.44.4');
                       ^

TypeError: Cannot read property 'get' of undefined
    at maxmind.open (/Users/prkumar/Projects/maxmind.js:5:24)
    at ReadFileContext.callback (/Users/prkumar/Projects/node_modules/maxmind/index.js:18:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)

```
var maxmind = require('maxmind');
maxmind.open('./GeoLite2-City.mmdb', (err, cityLookup) => {
  var city = cityLookup.get('66.6.44.4');
  console.log(city);
});
```

**Comment by pranshu1992** [comment]
I think I am missing something here.  This might not be an issue.

**Comment by pranshu1992** [comment]
The issue was in the path. You have to give the right path to the file. Thanks
